<?php

/**
 * @file
 * Contains pragmatica.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pragmatica_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.pragmatica':
            return 'Importa, gerencia e exibe dados de análises linguísticas do Grupo de Pesquisa - Pragmática (inter)linguística, intercultural e cross-cultural (GPP) (FFLCH-USP).';
    }
}


/**
 * Implements hook_theme().
 */
function pragmatica_theme($existing, $type, $theme, $path) {
  return [
    'pragmatica_label_list' => [
      'variables' => ['labels' => []],
    ],
    'pragmatica_label_item' => [
      'variables' => [
        'label' => NULL,
        'selections' => [],
        'label_type' => NULL,
      ],
    ],
    'pragmatica_label_type_item' => [
      'variables' => [
        'label_type' => NULL,

      ],
    ],
    'pragmatica_situation_list' => [
      'variables' => ['situations' => []],
    ],
    'pragmatica_situation_item' => [
      'variables' => [
        'situation' => NULL,
        'responses' => [],
      ],
    ],
    'pragmatica_response_item' => [
      'variables' => [
        'response' => NULL,
        'informant' => NULL,
        'situation' => NULL,
        'selections' => [],
        'labels' => [],
      ],
    ],
    'pragmatica_informant_item' => [
      'variables' => [
        'informant' => NULL,
        'responses' => [],
      ],
    ],
    'pragmatica_search_results' => [
      'variables' => [
        'query' => NULL,
        'results' => [],
      ],
    ]
  ];
}
