<?php

/**
 * @file
 * Contains pragmatica.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pragmatica_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.pragmatica':
            return 'Importa, gerencia e exibe dados de análises linguísticas do Grupo de Pesquisa - Pragmática (inter)linguística, intercultural e cross-cultural (GPP) (FFLCH-USP).';
    }
}


/**
 * Implements hook_theme().
 */
function pragmatica_theme($existing, $type, $theme, $path) {
  return [
    'pragmatica_source_list' => [
      'variables' => ['sources' => []],
    ],
    'pragmatica_source_item' => [
      'variables' => [
        'source' => NULL,
        'codings' => [],
      ]
    ],
    'pragmatica_code_list' => [
      'variables' => ['codes' => []],
    ],
    'pragmatica_code_item' => [
      'variables' => [
        'code' => NULL,
        'selections' => [],
      ],
    ],
    'pragmatica_search_results' => [
      'variables' => [
        'query' => NULL,
        'results' => [],
      ],
    ]
  ];
}
